version: "3"

services:
    rifaem2webapp:
        env_file:
            - rifaem2webapp/.env
        build:
            context: rifaem2webapp
        ports:
          - "5000:5000"

    nginx:
        image: nginx:latest
        volumes:
            - ./etc/nginx/templates:/etc/nginx/templates:ro
            - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - ./certbot/data:/var/www/certbot
        depends_on:
            - rifaem2webapp
        ports:
            - "80:80"
            - "443:443"

    certbot:
        container_name: certbot
        image: certbot/certbot:latest
        depends_on:
            - nginx
        command: >-
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email portopdr@gmail.com --agree-tos --no-eff-email
             -d rifado2.com
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - ./certbot/data:/var/www/certbot