version: "3"

services:
    rifaem2webapp:
        env_file:
            - rifaem2webapp/.env
        build:
            context: rifaem2webapp
        ports:
          - "5000:5000"

    nginx:
        image: nginx:stable
        volumes:
            - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
            - /etc/letsencrypt:/etc/letsencrypt
        depends_on:
            - rifaem2webapp
        ports:
            - "80:80"
            - "443:443"